"""Injection and jailbreak regex patterns."""

from __future__ import annotations

import re

INJECTION_PATTERNS: list[tuple[str, re.Pattern[str]]] = [
    (
        "ignore_previous",
        re.compile(
            r"(?i)(ignore|forget|disregard|override|bypass)\s+(?:\w+\s+)*"
            r"(previous|all|above|prior)\s+(?:\w+\s+)*"
            r"(instructions?|prompts?|rules?|guidelines?)",
        ),
    ),
    (
        "ignore_previous_fragment",
        re.compile(
            r"(?i)(ignore|forget|disregard|override|bypass)\s+(all\s+)?"
            r"(previous|prior|above|earlier)\b",
        ),
    ),
    (
        "ignore_previous_i18n",
        re.compile(
            r"(?i)(ignorar|olvidar|ignore)\s+(las\s+)?(instrucciones\s+)?(anteriores|previas)",
        ),
    ),
    (
        "persona_replacement",
        re.compile(
            r"(?i)(you\s+are\s+now|act\s+as|pretend\s+(to\s+be|you\s+are)|from\s+now\s+on\s+you)",
        ),
    ),
    (
        "reveal_prompt",
        re.compile(
            r"(?i)(reveal|show|display|print|output|repeat|tell\s+me)(?:\s+me)?\s+(your\s+)?"
            r"(system\s+)?(prompt|instructions?|rules?|guidelines?|configuration)",
        ),
    ),
    (
        "system_extraction_alt",
        re.compile(
            r"(?i)(what\s+(are|is)\s+your\s+(system\s+)?(prompt|instructions?|rules?)|"
            r"copy\s+your\s+(initial|system)\s+prompt)",
        ),
    ),
    (
        "developer_mode",
        re.compile(
            r"(?i)(developer\s+mode|DAN\s+mode|jailbreak|do\s+anything\s+now|no\s+restrictions?)",
        ),
    ),
    (
        "role_delimiter",
        re.compile(
            r"(<\/?system>|<\/?instruction>|\[\/INST\]|<\|im_end\|>)",
        ),
    ),
    (
        "fence_role_injection",
        re.compile(
            r"(?i)```\s*(system|assistant|instruction|prompt)\b",
        ),
    ),
    (
        "hex_encoding",
        re.compile(
            r"(?i)(?:\\x[0-9a-f]{2}){4,}",
        ),
    ),
    (
        "unicode_escape",
        re.compile(
            r"(?:\\u[0-9a-fA-F]{4}){3,}",
        ),
    ),
    (
        "indirect_instruction",
        re.compile(
            r"(?i)(when\s+you\s+read\s+this|important\s+instruction|hidden\s+instruction|"
            r"ignore\s+the\s+document\s+and|do\s+not\s+follow\s+the\s+user)",
        ),
    ),
    (
        "embedded_system_tag",
        re.compile(
            r"(?i)(<\s*system\s*>|<<\s*SYS\s*>>|\[INST\].*ignore)",
        ),
    ),
    (
        "fake_chat_delimiter",
        re.compile(
            r"(?i)---\s*(END\s+USER|SYSTEM|ASSISTANT|HUMAN)\s*---",
        ),
    ),
    (
        "chat_role_prefix",
        re.compile(
            r"(?i)(?:^|\n)\s*(Human|Assistant|System|User)\s*:\s*\S",
        ),
    ),
    (
        "bracket_system_tag",
        re.compile(
            r"(?i)\[(?:SYSTEM(?:\s+PROMPT)?|INST(?:RUCTION)?)\]",
        ),
    ),
    (
        "prior_rules_override",
        re.compile(
            r"(?i)(disregard|ignore|forget|override)\s+(prior|previous)\s+rules?\b",
        ),
    ),
    (
        "unrestricted_policy",
        re.compile(
            r"(?i)(unrestricted\s+mode|no\s+content\s+policy|"
            r"without\s+(any\s+)?content\s+(policy|filters|restrictions))",
        ),
    ),
    (
        "respond_as_unrestricted",
        re.compile(
            r"(?i)respond\s+as\s+if\s+you\s+(have|had)\s+no\s+"
            r"(content\s+)?(policy|restrictions|filters)",
        ),
    ),
    (
        "enable_jailbreak_mode",
        re.compile(
            r"(?i)enable\s+(developer|jailbreak|sudo|unrestricted)\s+mode",
        ),
    ),
    (
        "system_override",
        re.compile(
            r"(?i)(system\s+override|all\s+previous\s+directives?\s+(are\s+)?null\s+and\s+void|"
            r"comply\s+with\s+user\s+requests?\s+unconditionally)",
        ),
    ),
    (
        "guidelines_disabled",
        re.compile(
            r"(?i)(ethical\s+guidelines?\s+(have\s+been\s+)?disabled|"
            r"guidelines?\s+disabled\s+for\s+maintenance|proceed\s+without\s+them)",
        ),
    ),
    (
        "safety_filters_off",
        re.compile(
            r"(?i)(safety\s+filters?\s+(are\s+now\s+)?turned\s+off|"
            r"respond\s+freely\s+to\s+all\s+queries|without\s+restriction)",
        ),
    ),
    (
        "safety_waiver",
        re.compile(
            r"(?i)(safety\s+restrictions?\s+do\s+not\s+apply|"
            r"marked\s+as\s+internal\s+and\s+private)",
        ),
    ),
    (
        "evil_mode",
        re.compile(
            r"(?i)(activate\s+[A-Z][A-Z0-9_]+\s+mode|"
            r"in\s+[A-Z][A-Z0-9_]+\s+mode\s+you\s+respond|without\s+any\s+restrictions)",
        ),
    ),
    (
        "named_persona_hermes",
        re.compile(
            r"(?i)(you\s+are\s+(now\s+)?hermes\b|act\s+as\s+hermes\b|"
            r"meet\s+hermes\s*,?\s*an?\s+unrestricted)",
        ),
    ),
    (
        "named_persona_dan_stan",
        re.compile(
            r"(?i)(you\s+are\s+(now\s+)?(STAN|NRAF|DAN|AIM)\b|"
            r"do\s+anything\s+now\s+mode\s+enabled)",
        ),
    ),
    (
        "unrestricted_assistant_persona",
        re.compile(
            r"(?i)(unrestricted\s+(ai|assistant|language\s+model)|"
            r"without\s+(any\s+)?(ethical|moral)\s+(guidelines|constraints|limits))",
        ),
    ),
    (
        "helpful_red_team_framing",
        re.compile(
            r"(?i)(red[\s-]?team\s+(assistant|mode)|"
            r"help\s+me\s+test\s+(your\s+)?(safety|guardrails|filters))",
        ),
    ),
    # ── Hermes Agent (NousResearch/hermes-agent) threat_patterns alignment ──
    (
        "hermes_deception_hide",
        re.compile(
            r"(?i)do\s+not\s+(?:\w+\s+)*tell\s+(?:\w+\s+)*the\s+user",
        ),
    ),
    (
        "hermes_bypass_restrictions",
        re.compile(
            r"(?i)act\s+as\s+(if|though)\s+(?:\w+\s+)*you\s+(?:\w+\s+)*"
            r"(have\s+no|don't\s+have|do\s+not\s+have)\s+(?:\w+\s+)*"
            r"(restrictions|limits|rules)",
        ),
    ),
    (
        "hermes_translate_execute",
        re.compile(
            r"(?i)translate\s+.*\s+into\s+.*\s+and\s+(execute|run|eval)",
        ),
    ),
    (
        "hermes_html_comment_injection",
        re.compile(
            r"(?i)]*(?:ignore|override|system|secret|hidden)[^>]*-->",
        ),
    ),
    (
        "hermes_hidden_div",
        re.compile(
            r"(?i)<\s*div\s+style\s*=\s*['\"][\s\S]*?display\s*:\s*none",
        ),
    ),
    (
        "hermes_fake_update",
        re.compile(
            r"(?i)you\s+have\s+been\s+(?:\w+\s+)*(updated|upgraded|patched)\s+to",
        ),
    ),
    (
        "hermes_identity_override",
        re.compile(r"(?i)\bname\s+yourself\s+\w+"),
    ),
    (
        "hermes_env_unset_agent",
        re.compile(
            r"(?i)unset\s+\w*(?:CLAUDE|CODEX|HERMES|AGENT|OPENAI|ANTHROPIC)\w*",
        ),
    ),
    (
        "hermes_skill_authority_framing",
        re.compile(
            r"(?i)\[(?:important|system)\s*:\s*the\s+user\s+has\s+invoked",
        ),
    ),
    # ── Competitor corpus (NeMo YARA, llm-injection-guard, Rebuff-adjacent, ShadowProtect) ──
    (
        "simulate_unrestricted_role",
        re.compile(
            r"(?i)(simulate\s+being|roleplay\s+as)\s+.{0,80}"
            r"(without\s+(restrictions?|filters?|limits?|guidelines?))",
        ),
    ),
    (
        "html_comment_inject_marker",
        re.compile(r"(?i)<!--\s*INJECT"),
    ),
    (
        "encode_exfil_prompt",
        re.compile(
            r"(?i)(translate|encode)(\s+to\s+base64)?\s+(the\s+)?"
            r"(above|previous|system|prior)\s+(text|prompt|message|instructions?)",
        ),
    ),
    (
        "prompt_leak_verbatim",
        re.compile(
            r"(?i)repeat\s+(the\s+)?(above|everything|all)\s+"
            r"(verbatim|exactly|word\s+for\s+word)",
        ),
    ),
    (
        "persistent_override",
        re.compile(
            r"(?i)(in\s+your\s+next\s+response|from\s+now\s+on|for\s+all\s+future)\s+"
            r".{0,60}(ignore|disregard|forget|override|bypass)",
        ),
    ),
    (
        "null_byte_control",
        re.compile(r"[\x00-\x08\x0b\x0c\x0e-\x1f]"),
    ),
    (
        "jinja_template_inject",
        re.compile(r"\{\{|\{%"),
    ),
    (
        "markdown_js_link",
        re.compile(r"(?i)\]\(\s*javascript:"),
    ),
    (
        "markdown_script_tag",
        re.compile(r"(?i)<\s*script[^>]*>"),
    ),
    (
        "chat_section_header",
        re.compile(
            r"(?i)###\s*(Instruction|System|Human|Assistant|Context)\s*:",
        ),
    ),
    (
        "xml_chat_role_tag",
        re.compile(r"(?i)<\s*(system|assistant|human|user)\s*>"),
    ),
    (
        "bracket_chat_role_tag",
        re.compile(r"(?i)\[(?:SYSTEM|USER|ASSISTANT|HUMAN|INST)\]"),
    ),
    (
        "indirect_when_execute",
        re.compile(
            r"(?i)(when\s+you\s+(see|read)|if\s+you\s+read|upon\s+receiving)\s+"
            r".{0,40}(execute|run|perform)\s+(the\s+)?following",
        ),
    ),
    (
        "agent_chain_injection",
        re.compile(
            r"(?i)tell\s+(the\s+)?(next|all\s+other|every|other)\s+agent(s)?\s+to",
        ),
    ),
    (
        "forward_agent_instructions",
        re.compile(
            r"(?i)(forward|pass)\s+(this|the\s+following|these\s+instructions)\s+"
            r"to\s+(the\s+)?(next|all|other)\s+agent",
        ),
    ),
    (
        "skip_neglect_override",
        re.compile(
            r"(?i)(skip|neglect|omit|overlook|pay\s+no\s+attention\s+to)\s+"
            r"(?:\w+\s+)*(previous|prior|above|earlier)\s+"
            r"(?:\w+\s+)*(instructions?|directives?|rules?|guidelines?|context)",
        ),
    ),
    (
        "do_not_follow_rules",
        re.compile(
            r"(?i)do\s+not\s+(follow|obey)\s+(?:\w+\s+)*"
            r"(previous|prior|your|any)\s+(instructions?|rules?|guidelines?)",
        ),
    ),
    (
        "admin_god_mode",
        re.compile(r"(?i)\b(admin|debug|god|uncensored|unrestricted)\s+mode\b"),
    ),
    (
        "unlock_unrestricted_framing",
        re.compile(
            r"(?i)(unlock\s+mode|without\s+limitations?|no\s+restrictions|"
            r"bypass\s+(?:your\s+)?(?:safety\s+)?filters?)",
        ),
    ),
    (
        "credential_harvest_request",
        re.compile(
            r"(?i)(include|send|paste|copy|provide|extract|share|attach|leak|grab|pull)"
            r".{0,80}(session\s+token|api\s*key|secret|password|credentials?|bearer\s+token|"
            r"auth\s+token|cookie)",
        ),
    ),
    (
        "browser_secret_harvest",
        re.compile(
            r"(?i)(session\s+token|cookie|credentials?).{0,50}(browser\s+tab|devtools|"
            r"local\s+storage|session\s+storage)",
        ),
    ),
    (
        "quiet_side_channel",
        re.compile(
            r"(?i)quietly\s+(route|forward|send|relay|post|push).{0,80}"
            r"(channel|endpoint|webhook|proxy|maintenance)",
        ),
    ),
    (
        "maintenance_channel_exfil",
        re.compile(r"(?i)maintenance\s+channel"),
    ),
]
